# Generated by Django 6.0.5 on 2026-05-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='evidence_img',
            field=models.ImageField(blank=True, null=True, upload_to='evidence/', verbose_name='Ảnh minh chứng'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Đã duyệt/xác thực tài khoản'),
        ),
    ]
