# Generated by Django 6.0.5 on 2026-05-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('WELCOME', 'Welcome'), ('REPLY_POST', 'Reply Post'), ('REPLY_COMMENT', 'Reply Comment'), ('NEW_POST', 'New Post')], max_length=20),
        ),
    ]
