# Generated by Django 6.0.5 on 2026-05-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_commentvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='accepted_by_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='accepted_by_lecturer',
            field=models.BooleanField(default=False),
        ),
    ]
